### ISSUE TITLE
make REST management api protocol and version dynamic

### ISSUE THREAD

**Issue by xquery** [fgeorges/mlproj#1]
catering for https or different future version of REST Management api should be catered for.

**Comment by fgeorges** [comment]
@xquery I've added support for the following in the environment files:

    "apis": {
        "manage": {
            "root": "/manage/v42",
            "port": 6602,
            "ssl": true
        },
        "admin": {
            "root": "/admin/v1",
            "port": 8001,
            "ssl": false
        },
        "client": {
            "root": "/v1",
            "port": 8000,
            "ssl": false
        },
        "xdbc": {
            "root" : "",
            "port": 8000,
            "ssl": false
        }
    },

As usual, every part is optional, and overriding rules take place for each bit (you can e.g. put defaults in base.json, then import it in prod.json where you set only the ssl flag).

Still need to write doc.  Is that what you got in mind?

**Comment by fgeorges** [comment]
@xquery I am gonna assume this is indeed fixed and close the issue.

**Comment by fgeorges** [comment]
@xquery I assume it's fixed, feel free to reopen it or open another one if necessary.
