### ISSUE TITLE
Error installing mlproj

### ISSUE THREAD

**Issue by willsthompson** [fgeorges/mlproj#10]
I followed the [instructions to install from the EXPath Console readme](https://github.com/fgeorges/expath-ml-console#install): `sudo npm install mlproj -g`, and several errors occurred:

````
sudo npm install mlproj -g
node-pre-gyp WARN Pre-built binaries not installable for fsevents@1.2.4 and node@11.1.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/Users/willthompson/.nvm/versions/node/v11.1.0/lib/node_modules/mlproj/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64' 
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
...
````

I'm on a Mac running macOS 10.13, and my `npm --version => 6.4.1`. I was only able to get it to install after finding [an issue for similar problem on a different package](https://github.com/gdotdesign/elm-github-install/issues/21#issuecomment-332827661), and used this command:

    sudo npm i -g mlproj --unsafe-perm=true --allow-root

**Comment by fgeorges** [comment]
Hi @willsthompson. Thank you for reporting this!

Unfortunately I cannot reproduce the problem on my own Mac.  Also, I am not sure why the ML Console mentions `sudo` in that command (which is different from http://mlproj.org/doc/install).

- [x] remove `sudo` from ML Console install doc
- [x] add your solution/workaround above in the mlproj install doc
- [x] add the link below (about `EACCES`) in the mlproj install doc
- [x] add a link to the mlproj install doc in the ML Console install doc
- [x] do the same changes as in ML Console install doc, in the MLC website

Extra note. The following link on the npm website starts with "*If you see an `EACCES` error when you try to install a package globally, read this chapter*" : https://docs.npmjs.com/getting-started/fixing-npm-permissions.

**Comment by fgeorges** [comment]
Also, here is a thread with info that seems related more closely to your exact problem: https://github.com/nodejs/node-gyp/issues/454#issuecomment-315691803.

**Comment by fgeorges** [comment]
Done now.  This is all I can do as this is not an mlproj problem, but rather an NPM setup issue.

Note that the above comment mentions the MLC website, which has not been announced yet, but will replace the README file, eventually: http://mlconsole.org/.

**Comment by willsthompson** [comment]
Thanks @fgeorges! I read the article on `EACCES`, and I am actually installing Node via `nvm` as it recommends, but I have installed `nvm` with Homebrew, which I suspect is the problem. If there were a better way to do it via Homebrew I would, but I'm pretty committed to having everything managed by an OS package manager (I don't know if MacPorts has the same problem). I realize this is not your problem, but a Node problem, of which there are many :)

**Comment by willsthompson** [comment]
One more update (for anyone who stumbles across this issue down the road). After wiping `mlproj` and `nvm` (and Node, etc) packages, updating and cleaning up any warnings from Homebrew, and reinstalling `nvm`, then `mlproj` without `sudo`, everything seems to be working fine now. Thanks again.

**Comment by fgeorges** [comment]
Just a quick note that the initial issue was because of a dependency (of a dependency...), that has just been removed (I replaced chokidar by node-watch, which has 0 dependency, and actually works on Windows as well).
