### ISSUE TITLE
Add a .editorconfig file

### ISSUE THREAD

**Issue by dmcassel** [fgeorges/mlproj#4]
[EditorConfig](http://editorconfig.org/) is a plugin supported by many editors that configures an editor for a specific project's settings. [Example](https://github.com/marklogic/roxy/blob/master/.editorconfig)

**Comment by fgeorges** [comment]
Good idea, thanks.  Any idea why `trim_trailing_whitespace = false` in Roxy?

**Comment by dmcassel** [comment]
It's false for Markdown files, because the whitespace can be significant in that format. It's true for other formats.

**Comment by fgeorges** [comment]
Right, just discovered that a line with 2 spaces on their own makes a "line break".  Quite, ahem, surprising....

**Comment by fgeorges** [comment]
Added a config file for space indentation, of size 4.
