### ISSUE TITLE
Describe what a "project" is

### ISSUE THREAD

**Issue by sammefford** [fgeorges/mlproj#5]
When I saw this is a "project manager" I envisioned Microsoft Project.  After looking at the Introduction and Getting Started, I don't think that's what this is.  But while there's a lot of explanation of "how" to use it, I don't clearly understand "why" I would use it or "what" it is.  

In this sentence, what is a "MarkLogic project"?  "mlproj let you manage, deploy and configure MarkLogic projects"

**Comment by fgeorges** [comment]
Good point.  No, it is not at all "project" as in "Microsoft Project".

About your questions "why I would use it or what it is", I guess that if you don't get what it is, then you don't want to use it :-)

Basically, "project" has here the same definition than in any IDE: some vague notion of a consistent set of source code.  On MarkLogic, I guess an approximation would be "the set of source code in the modules database of an app server", but it is not necessarily true all the time.

What about this at the beginning of the "Get Started" guide?

> ### Projects
> 
> First of all, what do we mean by "project"?
> 
> With `mlproj`, a project is any consistent set of source code, typically deployed in an app server modules database.  This definition is rather vague (it is not a definition, really), and this is on purpose.  This gives you an idea of what it is meant to do, but it is up to you if you want to use it in another way.
>
> This is basically the same definition of "project" as in any IDE.
>
> In the code project management, there is rarely one-size-fits-all.  So `mlproj` tries not to constrain you too much, and you can use it with your project, whatever crazy its own rules are (to a very few exceptions.)

**Comment by sammefford** [comment]
Yes, having that "definition" in there seems helpful.  While most projects are used in unintended ways, I don't know if there's a need to mention that . . . people will naturally do it if they enjoy using it in the intended way.  Minor nit: I'd think "whatever crazy its own rules are (to a very few exceptions.)" should be "however crazy the rules are (with a very few exceptions.)"

**Comment by fgeorges** [comment]
Change committed and website updated.  Thank you!
