### ISSUE TITLE
File path does not have any slash

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj#6]
OS: Windows 10
MLversion : 8.0-5.4

Getting an error message when I run:

    mlproj -e prod setup

> Error: File path does not have any slash: d:\Workspace\GitHub\mlsamples\abc\abc\xproject\mlenvs\prod.json

Windows pathing issue? prod.json looks like this:

```
{
    "mlproj": {
        "format": "0.1",
        "import": "base.json",
        "connect": {
            "host": "prod.server",
            "user": "admin"
        },
        "databases": [{
            "id": "modules",
            "name": "@{code}-modules"
        }],
        "servers": [{
            "id": "app",
            "modules": {
                "idref": "modules"
            },
            "root": "/"
        }]
    }
}
```

**Comment by fgeorges** [comment]
Thank you for testing this on Windows, Chris, I kind of faired this would happen :-)  I've just published a new version, 0.21.0, that should fix this.  Can you try it, please?

`npm install mlproj -g` to upgrade, but I am sure you know that :-)

**Comment by eurochriskelly** [comment]
Works on windows now. Thanks!

**Comment by fgeorges** [comment]
Great, thank you for your help.  Any feedback on improvement and new features and PR welcome as well ;-)
