### ISSUE TITLE
mlproj should work from xproject directory

### ISSUE THREAD

**Issue by eurochriskelly** [fgeorges/mlproj#9]
Feature request.

A feature of npm is that no matter where you run it, it always climbs the directory tree and finds the first package.json. Then it runs as though that directory is the current working directory. This works great and means you can run commands with deterministic certainty no matter what directory you run from.

For example, if you try the command `npm run` anywhere, it will find the package.json and list the commands available. The commands will run from that directory. This means you don't have cd back up to the top level, run your command and `cd -` to get back where you are. `mlproj show` should give the status no matter where you are.

**Comment by fgeorges** [comment]
@eurochriskelly Any reason why you closed this one?
